version: '2'

services:
  db:
    build: ./db
    container_name: m0ney-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always

  m0ney:
    depends_on:
      - db
    build: .
    container_name: m0ney-system
    environment:
      EAR7H_ENV: "prod"
    ports:
      - "8080:8080"
