version: '2'

services:
  mysql:
    build: ./mysql
    container_name: m0ney-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "hello1"
    restart: always

  m0ney:
    depends_on:
      - mysql
    build: .
    container_name: m0ney-system
    ports:
      - "80:80"
