version: '2'

services:
  db:
    build: ./db
    container_name: m0ney-db
    environment:
      MYSQL_ROOT_PASSWORD: "hello1"
    restart: always

  m0ney:
    depends_on:
      - db
    build: .
    container_name: m0ney-system
    ports:
      - "8080:8080"
