version: '2'

services:
  db:
    build: ./db
    container_name: m0ney-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "/var/ear7h/m0ney/:/var/ear7h/m0ney/"
    restart: always

  server:
    depends_on:
      - db
    build: .
    container_name: m0ney-server
    environment:
      EAR7H_ENV: "prod"
    ports:
      - "8080:8080"